# Generated by Django 5.2.8 on 2025-11-07 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clie_id', models.AutoField(db_column='CLIE_ID', primary_key=True, serialize=False)),
                ('clie_nombre', models.CharField(db_column='CLIE_NOMBRE', max_length=100)),
                ('clie_fecha_nacimiento', models.DateField(blank=True, db_column='CLIE_FECHA_NACIMIENTO', null=True)),
                ('clie_telefono', models.CharField(blank=True, db_column='CLIE_TELEFONO', max_length=15, null=True)),
                ('clie_direccion', models.CharField(blank=True, db_column='CLIE_DIRECCION', max_length=150, null=True)),
                ('clie_numero_documento', models.CharField(blank=True, db_column='CLIE_NUMERO_DOCUMENTO', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'TBL_CLIENTES',
            },
        ),
        migrations.CreateModel(
            name='DatosMaestros',
            fields=[
                ('dama_id', models.AutoField(db_column='DAMA_ID', primary_key=True, serialize=False)),
                ('dama_nombre', models.CharField(db_column='DAMA_NOMBRE', max_length=100)),
                ('dama_valor', models.CharField(db_column='DAMA_VALOR', max_length=100)),
                ('dama_estado', models.IntegerField(db_column='DAMA_ESTADO', default=1)),
                ('dama_dependencia_id', models.ForeignKey(blank=True, db_column='DAMA_DEPENDENCIA_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_dependencia', to='core.datosmaestros')),
                ('dama_padre_id', models.ForeignKey(blank=True, db_column='DAMA_PADRE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_padre', to='core.datosmaestros')),
            ],
            options={
                'verbose_name': 'Dato Maestro',
                'verbose_name_plural': 'Datos Maestros',
                'db_table': 'TBL_DATOS_MAESTROS',
            },
        ),
        migrations.CreateModel(
            name='ClienteMembresia',
            fields=[
                ('clme_id', models.AutoField(db_column='CLME_ID', primary_key=True, serialize=False)),
                ('clime_fecha_inicio', models.DateField(db_column='CLIME_FECHA_INICIO')),
                ('clime_fecha_fin', models.DateField(blank=True, db_column='CLIME_FECHA_FIN', null=True)),
                ('clie_id', models.ForeignKey(db_column='CLIE_ID', on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('dama_membresia_id', models.ForeignKey(db_column='DAMA_MEMBRESIA_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membresias', to='core.datosmaestros')),
            ],
            options={
                'verbose_name': 'Membresía de Cliente',
                'verbose_name_plural': 'Membresías de Clientes',
                'db_table': 'TBL_CLIENTES_MEMBRESIAS',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='dama_tipo_documento',
            field=models.ForeignKey(db_column='DAMA_TIPO_DOCUMENTO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.datosmaestros'),
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('entr_id', models.AutoField(db_column='ENTR_ID', primary_key=True, serialize=False)),
                ('entr_nombre', models.CharField(db_column='ENTR_NOMBRE', max_length=100)),
                ('entr_fecha_nacimiento', models.DateField(blank=True, db_column='ENTR_FECHA_NACIMIENTO', null=True)),
                ('entr_telefono', models.CharField(blank=True, db_column='ENTR_TELEFONO', max_length=15, null=True)),
                ('entr_direccion', models.CharField(blank=True, db_column='ENTR_DIRECCION', max_length=150, null=True)),
                ('entr_numero_documento', models.CharField(blank=True, db_column='ENTR_NUMERO_DOCUMENTO', max_length=20, null=True)),
                ('dama_tipo_documento', models.ForeignKey(db_column='DAMA_TIPO_DOCUMENTO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrenadores', to='core.datosmaestros')),
            ],
            options={
                'verbose_name': 'Entrenador',
                'verbose_name_plural': 'Entrenadores',
                'db_table': 'TBL_ENTRENADORES',
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('clas_id', models.AutoField(db_column='CLAS_ID', primary_key=True, serialize=False)),
                ('clas_nombre', models.CharField(db_column='CLAS_NOMBRE', max_length=100)),
                ('clas_fecha', models.DateField(db_column='CLAS_FECHA')),
                ('dama_horario_id', models.ForeignKey(db_column='DAMA_HORARIO_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='core.datosmaestros')),
                ('entr_id', models.ForeignKey(db_column='ENTR_ID', on_delete=django.db.models.deletion.CASCADE, to='core.entrenador')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'TBL_CLASES',
            },
        ),
        migrations.CreateModel(
            name='EspecialidadEntrenador',
            fields=[
                ('esen_id', models.AutoField(db_column='ESEN_ID', primary_key=True, serialize=False)),
                ('dama_especialidad_id', models.ForeignKey(db_column='DAMA_ESPECIALIDAD_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especialidades', to='core.datosmaestros')),
                ('entr_id', models.ForeignKey(db_column='ENTR_ID', on_delete=django.db.models.deletion.CASCADE, to='core.entrenador')),
            ],
            options={
                'verbose_name': 'Especialidad de Entrenador',
                'verbose_name_plural': 'Especialidades de Entrenadores',
                'db_table': 'TBL_ESPECIALIDAD_ENTRENADOR',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaClase',
            fields=[
                ('ascl_id', models.AutoField(db_column='ASCL_ID', primary_key=True, serialize=False)),
                ('clas_id', models.ForeignKey(db_column='CLAS_ID', on_delete=django.db.models.deletion.CASCADE, to='core.clase')),
                ('clie_id', models.ForeignKey(db_column='CLIE_ID', on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name': 'Asistencia a Clase',
                'verbose_name_plural': 'Asistencias a Clases',
                'db_table': 'TBL_ASISTENCIAS_CLASES',
                'unique_together': {('clas_id', 'clie_id')},
            },
        ),
    ]
